### ISSUE TITLE
Basic chart doesn't render

### ISSUE THREAD

**Issue by mharmer** [Blissfully/elm-chartjs-webcomponent#2]
I'm trying to add a basic Doughnut chart and nothing seems to render. I observe a `<chart-component>` element added to the DOM but there are no attributes or child elements present.

I've included the Chart.js, in addition to this elm package.

I've attached a small reproduce case here: [ElmDoughnutTest.zip](https://github.com/Blissfully/elm-chartjs-webcomponent/files/3248996/ElmDoughnutTest.zip)

To run:
1. `elm make src/Main.elm --output=main.js`
2. Load the index.html in a browser and observe nothing rendered. index.html is pulling in the Chart.js source directly.

This might be me misunderstanding something in the library, and if so, maybe a small example could be added to the documentation or Github page.

**Comment by aaronwhite** [comment]
hi @mharmer - let me take a look! It's very possible I didn't translate the instructions properly or missed something else, but the fact that you included this sample should make it super simple to debug --- give me a few and I'll have some ideas!

**Comment by aaronwhite** [comment]
@mharmer - looks like you included `@blissfully/elm-chartjs-webcomponent` in your package.json, but didn't include the JS file inside of it as part of your JS that gets loaded into your index.html (and I agree, a sample should help.)

Not that you'd do this in dev/production, but for the sake of it rendering, if you included `<script src="node_modules/@blissfully/elm-chartjs-webcomponent/webcomponent/chart.js"></script>` in your `index.html`, it renders smashingly:

![image](https://user-images.githubusercontent.com/294426/58828024-6eebef00-8612-11e9-87af-28668f72ea91.png)

**Comment by aaronwhite** [comment]
Ideally, you'll want to include the webcomponent node module, and then include that JS file inside of it into your front end's JS bundling process. 

For what it's worth, I have a number of web component based Elm libs like this I'd like us to release, this is the integration thorn in all of them, so open to suggestions

**Comment by mharmer** [comment]
Awesome, that did it thanks!

**Comment by nikitaDanilenko** [comment]
Hi, I am new to using web components and I have some follow-up questions regarding the proper workflow that is hinted at above.

Is there a way to set up the `elm.json` (possibly together with `package.json`) to be able to use the Chart.js library with `elm reactor`? While the suggested script line works perfectly, this solution seems to require manual recompilation (so the compiled script is rebuilt), which runs counter to the reactive approach using `elm reactor`. This is probably, why @aaronwhite hinted at the fact that one wouldn't use this solution in development.

What are the precise steps to establish the proper workflow (the bundling part)? I lack the knowledge of the details mentioned above, but there appears to be a clearly cut out way, once you know the required steps. Would you mind sharing these steps?

Thank you very much in advance.
